// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agents": {
            "get": {
                "description": "Get a list of all registered agents/workers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "List agents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.AgentListResponse"
                        }
                    }
                }
            }
        },
        "/agents/{agentId}": {
            "get": {
                "description": "Get detailed information about a specific agent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "Get agent details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Agent"
                        }
                    },
                    "404": {
                        "description": "Agent not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/agents/{agentId}/drain": {
            "post": {
                "description": "Stop an agent from accepting new work (drain mode)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "Drain agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Agent not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/agents/{agentId}/resume": {
            "post": {
                "description": "Resume an agent to accept new work",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "Resume agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Agent not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/agents/{agentId}/status": {
            "get": {
                "description": "Get status information for a specific agent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "Get agent status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.AgentStatus"
                        }
                    },
                    "404": {
                        "description": "Agent not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/artifacts": {
            "get": {
                "description": "Get a paginated list of artifacts with optional filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artifacts"
                ],
                "summary": "List artifacts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by job ID",
                        "name": "jobId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by run ID",
                        "name": "runId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of artifacts to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cursor for pagination",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by artifact type (pdf|pptx|zip|log)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ArtifactListResponse"
                        }
                    }
                }
            }
        },
        "/artifacts/{artifactId}": {
            "get": {
                "description": "Get metadata for a specific artifact",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artifacts"
                ],
                "summary": "Get artifact metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Artifact ID",
                        "name": "artifactId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Artifact"
                        }
                    },
                    "404": {
                        "description": "Artifact not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an artifact",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artifacts"
                ],
                "summary": "Delete artifact",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Artifact ID",
                        "name": "artifactId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Artifact not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/artifacts/{artifactId}/download": {
            "get": {
                "description": "Download the artifact file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "artifacts"
                ],
                "summary": "Download artifact",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Artifact ID",
                        "name": "artifactId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Artifact file",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Artifact not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate and receive access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Logout and invalidate the current session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Refresh an access token using a refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh token",
                "parameters": [
                    {
                        "description": "Refresh token request",
                        "name": "refresh",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns 200 OK if the service is alive",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check (liveness)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/jobs": {
            "get": {
                "description": "Get a paginated list of jobs with optional filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "List jobs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of jobs to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cursor for pagination",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status (queued|running|succeeded|failed)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by workflow name",
                        "name": "workflow",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.JobListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Submit a new job to be processed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Create a new job",
                "parameters": [
                    {
                        "description": "Job creation request",
                        "name": "job",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateJobRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.CreateJobResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/jobs/{jobId}": {
            "get": {
                "description": "Get detailed information about a specific job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Get job details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Job"
                        }
                    },
                    "404": {
                        "description": "Job not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Cancel a running or queued job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Cancel a job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Job not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/jobs/{jobId}/events": {
            "get": {
                "description": "Stream job status updates via Server-Sent Events (SSE)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Stream job events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Event stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/jobs/{jobId}/logs": {
            "get": {
                "description": "Get aggregated logs for a job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Get job logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of log lines to return",
                        "name": "tail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RFC3339 timestamp to filter logs from",
                        "name": "since",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.JobLogsResponse"
                        }
                    },
                    "404": {
                        "description": "Job not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/jobs/{jobId}/result": {
            "get": {
                "description": "Get the latest result summary for a job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Get job result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.JobResult"
                        }
                    },
                    "404": {
                        "description": "Job not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/jobs/{jobId}/retry": {
            "post": {
                "description": "Retry a failed or cancelled job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Retry a job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CreateJobResponse"
                        }
                    },
                    "404": {
                        "description": "Job not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/jobs/{jobId}/steps": {
            "get": {
                "description": "Get a list of workflow steps for a job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "List job steps",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.JobStep"
                            }
                        }
                    },
                    "404": {
                        "description": "Job not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/jobs/{jobId}/steps/{stepId}": {
            "get": {
                "description": "Get detailed information about a workflow step",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Get step details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Step ID",
                        "name": "stepId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.JobStep"
                        }
                    },
                    "404": {
                        "description": "Step not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/jobs/{jobId}/steps/{stepId}/logs": {
            "get": {
                "description": "Get logs for a specific workflow step",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Get step logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Step ID",
                        "name": "stepId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.JobLogsResponse"
                        }
                    },
                    "404": {
                        "description": "Step not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/queue": {
            "get": {
                "description": "Get queue statistics and metrics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queue"
                ],
                "summary": "Get queue statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.QueueStats"
                        }
                    }
                }
            }
        },
        "/queue/items": {
            "get": {
                "description": "Get a paginated list of queue items with optional filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queue"
                ],
                "summary": "List queue items",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of items to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cursor for pagination",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by state (pending|leased|done|dead)",
                        "name": "state",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.QueueItemListResponse"
                        }
                    }
                }
            }
        },
        "/queue/requeue": {
            "post": {
                "description": "Requeue a job in the queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queue"
                ],
                "summary": "Requeue a job",
                "parameters": [
                    {
                        "description": "Requeue request",
                        "name": "requeue",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RequeueRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Returns 200 OK if the service is ready to accept requests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/runs": {
            "get": {
                "description": "Get a paginated list of runs with optional filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "List runs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of runs to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cursor for pagination",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by job ID",
                        "name": "jobId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RunListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Start a new run for a job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Create a new run",
                "parameters": [
                    {
                        "description": "Run creation request",
                        "name": "run",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateRunRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.CreateRunResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/runs/{runId}": {
            "get": {
                "description": "Get detailed information about a specific run",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Get run details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Run ID",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Run"
                        }
                    },
                    "404": {
                        "description": "Run not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Cancel a running or pending run",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Cancel a run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Run ID",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Run not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Returns the service name, version, and commit information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get version information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.VersionResponse"
                        }
                    }
                }
            }
        },
        "/workflows": {
            "get": {
                "description": "Get a list of all available workflows",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflows"
                ],
                "summary": "List workflows",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.WorkflowListResponse"
                        }
                    }
                }
            }
        },
        "/workflows/validate": {
            "post": {
                "description": "Validate input parameters for a workflow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflows"
                ],
                "summary": "Validate workflow input",
                "parameters": [
                    {
                        "description": "Workflow validation request",
                        "name": "workflow",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ValidateWorkflowRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ValidateWorkflowResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workflows/{name}": {
            "get": {
                "description": "Get schema and metadata for a specific workflow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflows"
                ],
                "summary": "Get workflow details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Workflow"
                        }
                    },
                    "404": {
                        "description": "Workflow not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Agent": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastSeen": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.AgentListResponse": {
            "type": "object",
            "properties": {
                "agents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Agent"
                    }
                }
            }
        },
        "api.AgentStatus": {
            "type": "object",
            "properties": {
                "activeJobs": {
                    "type": "integer"
                },
                "completedJobs": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "isDraining": {
                    "type": "boolean"
                },
                "lastSeen": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.Artifact": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "jobId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "runId": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/api.ArtifactType"
                }
            }
        },
        "api.ArtifactListResponse": {
            "type": "object",
            "properties": {
                "artifacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Artifact"
                    }
                },
                "cursor": {
                    "type": "string"
                },
                "hasMore": {
                    "type": "boolean"
                }
            }
        },
        "api.ArtifactType": {
            "type": "string",
            "enum": [
                "pdf",
                "pptx",
                "zip",
                "log"
            ],
            "x-enum-varnames": [
                "ArtifactTypePDF",
                "ArtifactTypePPTX",
                "ArtifactTypeZIP",
                "ArtifactTypeLog"
            ]
        },
        "api.CreateJobRequest": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "object",
                    "additionalProperties": true
                },
                "meta": {
                    "type": "object",
                    "additionalProperties": true
                },
                "workflow": {
                    "type": "string"
                }
            }
        },
        "api.CreateJobResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "api.CreateRunRequest": {
            "type": "object",
            "properties": {
                "jobId": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "api.CreateRunResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "api.Job": {
            "type": "object",
            "properties": {
                "completedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "input": {
                    "type": "object",
                    "additionalProperties": true
                },
                "meta": {
                    "type": "object",
                    "additionalProperties": true
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/api.JobStatus"
                },
                "updatedAt": {
                    "type": "string"
                },
                "workflow": {
                    "type": "string"
                }
            }
        },
        "api.JobListResponse": {
            "type": "object",
            "properties": {
                "cursor": {
                    "type": "string"
                },
                "hasMore": {
                    "type": "boolean"
                },
                "jobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Job"
                    }
                }
            }
        },
        "api.JobLogsResponse": {
            "type": "object",
            "properties": {
                "jobId": {
                    "type": "string"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.LogEntry"
                    }
                }
            }
        },
        "api.JobResult": {
            "type": "object",
            "properties": {
                "artifacts": {
                    "description": "artifact IDs",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "completedAt": {
                    "type": "string"
                },
                "jobId": {
                    "type": "string"
                },
                "result": {
                    "type": "object",
                    "additionalProperties": true
                },
                "status": {
                    "$ref": "#/definitions/api.JobStatus"
                }
            }
        },
        "api.JobStatus": {
            "type": "string",
            "enum": [
                "queued",
                "running",
                "succeeded",
                "failed",
                "cancelled"
            ],
            "x-enum-varnames": [
                "JobStatusQueued",
                "JobStatusRunning",
                "JobStatusSucceeded",
                "JobStatusFailed",
                "JobStatusCancelled"
            ]
        },
        "api.JobStep": {
            "type": "object",
            "properties": {
                "completedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "input": {
                    "type": "object",
                    "additionalProperties": true
                },
                "jobId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "output": {
                    "type": "object",
                    "additionalProperties": true
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/api.StepStatus"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "api.LogEntry": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "stepId": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "api.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "api.LoginResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "expiresIn": {
                    "type": "integer"
                }
            }
        },
        "api.QueueItem": {
            "type": "object",
            "properties": {
                "completedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "type": "string"
                },
                "jobId": {
                    "type": "string"
                },
                "leasedAt": {
                    "type": "string"
                },
                "state": {
                    "$ref": "#/definitions/api.QueueState"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "api.QueueItemListResponse": {
            "type": "object",
            "properties": {
                "cursor": {
                    "type": "string"
                },
                "hasMore": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.QueueItem"
                    }
                }
            }
        },
        "api.QueueState": {
            "type": "string",
            "enum": [
                "pending",
                "leased",
                "done",
                "dead"
            ],
            "x-enum-varnames": [
                "QueueStatePending",
                "QueueStateLeased",
                "QueueStateDone",
                "QueueStateDead"
            ]
        },
        "api.QueueStats": {
            "type": "object",
            "properties": {
                "dead": {
                    "type": "integer"
                },
                "done": {
                    "type": "integer"
                },
                "leased": {
                    "type": "integer"
                },
                "pending": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.RefreshRequest": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "api.RequeueRequest": {
            "type": "object",
            "properties": {
                "jobId": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "api.Run": {
            "type": "object",
            "properties": {
                "completedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "jobId": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": true
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/api.RunStatus"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "api.RunListResponse": {
            "type": "object",
            "properties": {
                "cursor": {
                    "type": "string"
                },
                "hasMore": {
                    "type": "boolean"
                },
                "runs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Run"
                    }
                }
            }
        },
        "api.RunStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "succeeded",
                "failed",
                "cancelled"
            ],
            "x-enum-varnames": [
                "RunStatusPending",
                "RunStatusRunning",
                "RunStatusSucceeded",
                "RunStatusFailed",
                "RunStatusCancelled"
            ]
        },
        "api.StepStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "succeeded",
                "failed",
                "skipped"
            ],
            "x-enum-varnames": [
                "StepStatusPending",
                "StepStatusRunning",
                "StepStatusSucceeded",
                "StepStatusFailed",
                "StepStatusSkipped"
            ]
        },
        "api.ValidateWorkflowRequest": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "object",
                    "additionalProperties": true
                },
                "workflow": {
                    "type": "string"
                }
            }
        },
        "api.ValidateWorkflowResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "api.VersionResponse": {
            "type": "object",
            "properties": {
                "commit": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "api.Workflow": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "schema": {
                    "type": "object",
                    "additionalProperties": true
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "api.WorkflowListResponse": {
            "type": "object",
            "properties": {
                "workflows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Workflow"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3333",
	BasePath:         "/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Agent Project Manager API",
	Description:      "REST API for the Agent Project Manager daemon. Orchestrates agent-based LLM workflows.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
